version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && gem install bundler -v 2.0.1 && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/test-ecov
    ports:
      - "3000:3000"
    depends_on:
      - db
